#!/bin/bash
set -e

# This is a special script that is run at the end of the main Strap
# process.  Use it to provide any final customizations that need to
# to be run after everything else finishes.

#---------------------------------------------------------------------
# Personal setup
# If you have another personal repository that has additional
# configuration, such as license keys, you can call out to it here.
#---------------------------------------------------------------------
# personal="$HOME/src/personal-configuration/setup.sh"
#[ -f "$personal" ] && bash "$personal"

