#!/usr/bin/env bash

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
USER_DOTFILES=$(pwd -P)

ensure_dotfile_link() {
  HOMEFILE="$HOME/$1"
  DOTFILE="$USER_DOTFILES/$1"
     
  if [ -L "$HOMEFILE" ] && ! [ -d "$DOTFILE" ]; then
    ln -sfv "$DOTFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE"
    ln -sv "$DOTFILE" "$HOMEFILE"
  fi
}

ensure_dotfile_link .gitconfig
ensure_dotfile_link .Brewfile

#---------------------------------------------------------------------
# Projects.  The list of supported projects comes from
# https://github.com/daptiv/dotfiles/tree/master/projects/
# Each folder name is a project.  Just include the folder name as
# outlined below, to include that project in your setup.
#---------------------------------------------------------------------
SETUP_SCRIPT="$HOME/.daptiv-dotfiles/projects/setup"
if [ -f "$SETUP_SCRIPT" ]; then
	echo "Configuring projects"
	# PPM is setup by the base scripts - no need to manual include
	# bash "$SETUP_SCRIPT" ttm
	# bash "$SETUP_SCRIPT" ppmspa
fi


